# docker-compose.yml
#version: '3'

services:
  tool:
    container_name: kanzleitool
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - ORIGIN=https://svelte.meratos.com
